# -*- coding: utf-8 -*-
"""Handling missing values.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hkiyOitGCoqcAhsB4rvRmV1RYJBnpPbs
"""

import pyspark

import pandas as pd

from pyspark.sql import SparkSession
spark=SparkSession.builder.appName('Practise').getOrCreate()

df_pyspark=spark.read.csv('/content/test2.csv',header=True,inferSchema=True)

df_pyspark.show()

df_pyspark.printSchema()

df_pyspark.show()

"""#Drop The Columns"""

df_pyspark=df_pyspark.drop('Name')

df_pyspark.show()

"""remove rows containing missing or null values from your dataset"""

df_pyspark.na.drop().show()

"""#any==how
to clean our dataset by instantly removing any rows that contain missing or null values
"""

df_pyspark.na.drop(how="any").show()

"""
to keep only rows that have at least 3 non-null values and immediately display the cleaned"""

##Threshold
df_pyspark=df_pyspark.na.drop(how="any",thresh=3)

df_pyspark.show()

##Subset
df_pyspark.na.drop(how="any",subset=['age'])

df=df_pyspark.show()

##Filling the Missing Vlaues
df_pyspark=df_pyspark.na.fill('Missing Values',['Experience','age'])

df_pyspark.show()

df_pyspark.printSchema()

from pyspark.ml.feature import Imputer

imputer = Imputer(
    inputCols=['age', 'Experience', 'Salary'],
    outputCols=["{}_imputed".format(c) for c in ['age', 'Experience', 'Salary']]
    ).setStrategy("median")

"""##ADD imputation Cols to df"""

imputer.fit(df_pyspark).transform(df_pyspark).show()

"""# Add imputation cols to df"""

imputer.fit(df_pyspark).transform(df_pyspark).show()

